install! 'cocoapods', :generate_multiple_pod_projects => true
project 'IJKMediaMacDemo.xcodeproj'

target 'IJKMediaMacDemo' do
    use_frameworks!
    platform :osx, '10.13'
    pod 'IJKMediaPlayerKit', :path => '../../'
end