install! 'cocoapods', :generate_multiple_pod_projects => true

target 'IJKMediaMacDemo' do
    pod 'IJKMediaPlayerKit', :path => '../../'
    project 'IJKMediaMacDemo.xcodeproj'
    platform :osx, '10.11'
    use_frameworks!
end