#1.7.0
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'IJKMediaDemo2' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
  
    # Pods for IJKMediaDemo2
  
    platform :osx, '10.11'
  
    pod 'IJKMediaPlayerKit', :path => '../../'
  
  end